### ISSUE TITLE
execution error -- libgomp: Thread creation failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by grendon** [sequencing/isaac_aligner#10]
The reference genome  TAIR10 for arabidopsis thaliana. Size 119481543
The Sakata reads files come from this url
http://1001genomes.org/data/JGI/JGIHeazlewood2011/releases/current/TAIR10/strains/
#PE reads 60173258
read length 100
avg depth 36.87
std depth 313.73

Several benchmarking  jobs were submitted to  an SGI UV1000 node with 384 Intel Xeon X7542 and 2TB of memory.
I assigned 150gb of memory to each job.
Number of cores assigned to each job varied = 36, 24, 16, 8
All but one job finished successfully. The job with 36 cores failed. Below are the last few lines of the error log.

2014-07-25 14:56:11     [2b53393de700]  Opened fastq stream on /home/a-m/gren\
don/tair-isaac-pipeline_test/index/sakata_reads/lane1_read1.fastq
2014-07-25 14:56:11     [2b53393de700]  Opened fastq stream on /home/a-m/gren\
don/tair-isaac-pipeline_test/index/sakata_reads/lane1_read2.fastq
2014-07-25 14:56:11     [2b53393de700]  Resetting Fastq data for 5000000 clus\
ters
2014-07-25 14:56:13     [2b53393de700]  Resetting Fastq data done for 5000000\
 clusters
2014-07-25 14:56:54     [2b53393de700]  Loading Fastq data done. Loaded 50000\
00 clusters for TileMetadata(1101, 1, 1, 5000000, 0)
2014-07-25 14:56:54     [2b53393de700]  Sorting matches by barcode for TileMe\
tadata(1101, 1, 1, 5000000, 0)
2014-07-25 14:56:54     [2b53391dd700]  Loading matches for TileMetadata(1101\
, 2, 1, 5000000, 1)

libgomp: Thread creation failed: Resource temporarily unavailable

**Comment by rpetrovski** [comment]
Replaced gnu parallel sort with home-made one. Please try iSAAC-01.15.01.28.

Roman.

**Comment by chunhualiao** [comment]
I just saw a similar error with gcc 4.9.2.  The input code is a simple OpenMP nested parallelism code. 
The problem is the workstation has 72 logical processors. The program will try to start 72*72 threads by default, which triggers "libgomp: Thread creation failed: Resource temporarily unavailable" .

The solution is to limit the number of threads at each level of parallelism, using num_threads() clause.
