### ISSUE TITLE
Error: isac alighner

### ISSUE THREAD

**Issue by kvshams** [sequencing/isaac_aligner#19]
Hello,
 I am using isaac alighner command as follows and it is working fine with 1TB RAM system. When I am trying the same command in 128 GB RAM system the system is giving error. Even I have reduced the memory with -m option, still getting the same issue. The command is as follows

$ /opt/illumina/Isaac/Isaac-00.13.02.01/bin/isaac-align -r /home/softwarelibrary/hg19_isacRef/Homo_sapiens/UCSC/hg19/Sequence/IsaacIndex/sorted-reference.xml -b ../Sample_1/ --base-calls-format fastq-gz --default-adapters AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT_,_CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT --base-quality-cutoff 20 --variable-fastq-read-length 1 --ignore-neighbors 1 --ignore-missing-bcls 1 --ignore-missing-filters 1 --memory-limit 64

The error I am getting is

2016-09-07 11:17:14     [0x1e92c30]     ERROR: ****\* Internal Program Error - assertion (!compressedStream.good()) failed in std::streamsize isaac::io::InflateGzipDecompressor<ContainterT>::read(std::istream&, char*, std::streamsize) [with ContainterT = isaac::common::FiniteCapacityVector<char, 4096ul>; std::streamsize = long int; std::istream = std::basic_istream<char>]:/export/scratch/rpetrovski/workspace2/iSAAC/src/c++/include/io/InflateGzipDecompressor.hh(181): When no bytes come out of decompressor expecting the input stream to be over
Segmentation fault (core dumped)

Please help to sort the issue

**Comment by rpetrovski** [comment]
iSAAC-00 is not supported anymore. Please consider iSAAC-03: https://github.com/Illumina/Isaac3

**Comment by kvshams** [comment]
Hi Rpetrovski ,
Thanks for your replay. But I have seen that the performance of Isaac-2 and 3 is quiet nasty as compared to the 00 version in terms of unambiguous mapping to the human hole genome. The same data set is giving 15.0 map quality and 250X coverage for 496,946,054 mapped reads were as the 00 version is giving 35X with an average mapQ of 52.3. How it is possible? I am using the default option for both.

**Comment by rpetrovski** [comment]
It is hard to say what could cause that particular pileup without seeing the data. Would you be able to make the input dataset available? Can you please specify the reference and the genomic region that causes your concern?

In general, each subsequent version of iSAAC historically had better view of the reference genome than the previous one. It is possible that you are seeing alignments that iSAAC-00 simply could not make. The lower MAPQ indicates that despite having placed the read, the more recent aligner believes that there are alternative placements that are relatively equivalent. In some cases, the solution to pileups can be as simple as ignoring all the alignments below certain MAPQ.

Roman.

**Comment by kvshams** [comment]
Thanks Roman for the quick Replay. Here I am attaching the QCs of the alighnemnt from both Isaac-2 and HAS and isaac from HAS v0.9. Please see the discrepancies on the results (MapQs and Coverage).
![sample_1_has](https://cloud.githubusercontent.com/assets/6705324/18399510/3562de2c-7686-11e6-938e-ff508c43ad7d.png)
![sample_1_i2](https://cloud.githubusercontent.com/assets/6705324/18399515/3d5e37f2-7686-11e6-8d96-70d8b5e19f9e.png)
![sample_2_i2](https://cloud.githubusercontent.com/assets/6705324/18399516/3dd59cb6-7686-11e6-9e20-a078cc6c878b.png)
![sample_3_i2](https://cloud.githubusercontent.com/assets/6705324/18399518/3df8e252-7686-11e6-8119-13400a26bbaf.png)
![sample_4_i0](https://cloud.githubusercontent.com/assets/6705324/18399519/3dfa5f6a-7686-11e6-849e-c7f51183ff47.png)
![sample_4_i2](https://cloud.githubusercontent.com/assets/6705324/18399517/3df72444-7686-11e6-9176-9d266349c318.png)

All these samples are comparable numbers of paired end human genome reads generated on hiseq 2500 using truseq reagents. Am missing any thing during the alighnment options. I am using the default command line provided in the site/manual. The genome is downloaded from iGenome for isaac2.

I have done 30 Genome and all of them I am facing the same problem. Let me try any public data and see how it behave.

Please let me know any further information required

Shams

**Comment by rpetrovski** [comment]
This does indeed look strange. Have you used the latest of iSAAC-02/03?
Please let me know if you get the same results with public data.

One good source of public data is Illumina Platinum Genomes
http://www.illumina.com/platinumgenomes/

Roman.

**Comment by kvshams** [comment]
Yeah its looking strange. I have used the Isaac2 downloaded  last week (Version: iSAAC-02.16.03.29). Just downloading the data. Will update when the data is ready.
Shams
