### ISSUE TITLE
Version 1.14.02.06

### ISSUE THREAD

**Issue by wiedenhoeft** [sequencing/isaac_aligner#21]
I am reading a paper which references iSAAc version 1.14.02.06. However, I don't see this version here. Is that a misprint, or are there other versions published elsewhere? Thanks!

**Comment by rpetrovski** [comment]
1.14.02.06 had usability issues, so it never got tagged on the github. The next available version is 1.14.02.10. It should be equivalent to the one used in the paper in terms of data processing results.

Please use the [changelog](https://github.com/sequencing/isaac_aligner/blob/master/src/Changes) for your reference.

Please note that the current publicly available version is [iSAAC-03](https://github.com/Illumina/Isaac3)

Roman.

**Comment by wiedenhoeft** [comment]
Thanks for the info and the quick response!
